AllCops:
  SuggestExtensions: false
  NewCops: enable

Metrics/BlockLength:
  Exclude: 
    - spec/**/*

Naming/MethodParameterName:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
